datasources:
  default:
    url: jdbc:h2:mem:testdb;MODE=POSTGRES;DATABASE_TO_LOWER=TRUE
    driverClassName: org.h2.Driver

##
# jpa
##
jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true
#jpa.default.properties.hibernate.format_sql: true

##
# Habilita log do contexto transacional
##
logger:
  levels:
    io.micronaut.transaction: DEBUG